### ISSUE TITLE
Can't seem to ask for user location permission

### ISSUE THREAD

**Issue by redimongo** [afollestad/assent#22] opened 2021-06-08 08:07 UTC
I have followed the how to guide and I just can't get it to work. All I want is for the location permission to popup.

```kotlin
 val rationaleHandler = createSnackBarRationale(rootView) {
            onPermission(Permission.ACCESS_COARSE_LOCATION, "Test rationale #1, please accept!")
            onPermission(Permission.ACCESS_FINE_LOCATION, "Test rationale #2, please accept!")

        }


                val result = awaitPermissionsResult(Permission.ACCESS_FINE_LOCATION,Permission.ACCESS_FINE_LOCATION
                    rationaleHandler = rationaleHandler
                )
                statusText.text = result.toString()
            }
            .launchIn(lifecycleScope)
```

That code has errors and does not work in the latest version of kotlin.

**Comment by afollestad** [comment] 2022-12-26 00:14
Likely a duplicate of https://github.com/afollestad/assent/issues/21

**Closed by afollestad** 2022-12-26 00:14 UTC
