### ISSUE TITLE
`askForPermissions` isn't triggering the `AssentResult` callback on Android 11?

### ISSUE THREAD

**Issue by genneralJ** [afollestad/assent#24] opened 2021-07-09 08:53 UTC
With `3.0.0-RC4`…

```kotlin
askForPermissions(
  listOf(
    Permission.WRITE_EXTERNAL_STORAGE ,
    Permission.READ_EXTERNAL_STORAGE ,
    Permission.READ_PHONE_STATE,//
    Permission.CAMERA,//
  )
）
```

When all permissions are agreed (only running in use), calling `askForPermissions` again does not trigger the callback with an `AssentResult`.

After testing Android10 or below, calling again can be called back
当所有权限都同意（仅在使用中运行）后 再次调用askForPermissions没有触发回调AssentResult
经测试Android10以下再次调用可以回调

**Comment by afollestad** [comment] 2022-12-26 00:13
Appears to be a duplicate of https://github.com/afollestad/assent/issues/21

**Closed by afollestad** 2022-12-26 00:13 UTC
